require "keymaps"
require "options"
require "lazy-config"
require "whichkey"
require "bufferline-config"
require "lualine-config"
require "hop-config"
require "indentline-config"
require "nvim-tree-config"
require "telescope-config"
require "git-config"
require "alpha-config"
require "treesitter-config"
require "lsp-config"
require "autopairs-config"
require "undotree-config"

vim.cmd[[ colorscheme tokyonight ]]
